services:
  minima-harness:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION=sa-east-1
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
